# Generated by Django 6.1.1 on 2026-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('circulo', models.CharField(blank=True, choices=[('VM', 'Vermelho'), ('AZ', 'Azul'), ('AM', 'Amarelo'), ('LA', 'Laranja'), ('VD', 'Verde')], max_length=2, null=True)),
            ],
        ),
    ]
